### ISSUE TITLE
Changes for modeci.org?

### ISSUE THREAD

**Issue by pgleeson** [MetaCell/ModECIWebsite-Staging#40]
I've changed the DNS settings of modeci.org (based on [this](https://dafero.wordpress.com/2020/02/19/how-to-configure-github-pages-with-a-custom-ionos-old-11-domain/)), and now it does show the website (rather than redirect to https://modeci.github.io/Website), but there are isues with display.

Do these lines need to be adjusted: https://github.com/ModECI/Website/blob/main/_config.yml#L1-L2?

**Comment by vidhya-metacell** [comment]
@pgleeson I can see the website live on http://modeci.org/. Are you facing any issue?
cc @tarelli 
<img width="1440" alt="Screenshot 2021-05-21 at 9 41 58 PM" src="https://user-images.githubusercontent.com/71261494/119167516-90ec0f80-ba7d-11eb-976c-3eb03eff9d93.png">

**Comment by tarelli** [comment]
@pgleeson @vidhya-metacell works also for me

**Comment by pgleeson** [comment]
Yes, I made the change in _config.yml and it fixed things.
